services:
  ranking-ms:
    container_name: nemo-retriever-ranking-microservice
    image: nvcr.io/nim/nvidia/nv-rerankqa-mistral-4b-v3:1.0.1
    volumes:
    - ${MODEL_DIRECTORY}:/opt/nim/.cache
    ports:
    - "1976:8000"
    expose:
    - "8000"
    environment:
      NGC_API_KEY: ${NGC_API_KEY}
    user: "${USERID:-1000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 20s
      retries: 100
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ['${RANKING_MS_GPU_ID:-0}']
              count: ${INFERENCE_GPU_COUNT:-all}
              capabilities: [gpu]
 

